//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examenDDLH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class genskuscat
    {
        public int sku { get; set; }
        public decimal codigoProveedor { get; set; }
        public string Estilo { get; set; }
        public string descripcionEstilo { get; set; }
        public string estatus { get; set; }
        public decimal precioOriginal { get; set; }
        public string tipoProducto { get; set; }
        public decimal codigoDepto { get; set; }
        public decimal codigoSubDepto { get; set; }
        public decimal codigoClase { get; set; }
        public decimal codigoSubClase { get; set; }
        public string descripcionCorta { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string codigoTA { get; set; }
        public string codigoTalla { get; set; }
        public decimal codigoColor { get; set; }
        public string codigoUnidadDeMedida { get; set; }
        public string codigoTemporada { get; set; }
        public int codigoMarca { get; set; }
        public System.DateTime fechaActualizacion { get; set; }
    }
}
