//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examenDDLH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gentiendascat
    {
        public int codigoTienda { get; set; }
        public Nullable<int> codigoMarca { get; set; }
        public string descripcionTienda { get; set; }
        public string estatus { get; set; }
        public string tipo { get; set; }
        public string direccion { get; set; }
        public string colonia { get; set; }
        public string referencia { get; set; }
        public string ciudad { get; set; }
        public int codigoEstado { get; set; }
        public string codigoPostal { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string descripcionCorta { get; set; }
        public System.DateTime fechaApertura { get; set; }
        public System.DateTime fechaCierre { get; set; }
        public string tiendaBodega { get; set; }
        public int centroDeDistribucion { get; set; }
        public int distrito { get; set; }
        public int zona { get; set; }
        public string codigoImpuesto { get; set; }
        public string ipAdmin { get; set; }
        public string ipImpresora { get; set; }
        public string servidor { get; set; }
        public string baseDatos { get; set; }
        public byte[] usuarioBaseDatos { get; set; }
        public byte[] passwordBaseDatos { get; set; }
        public string gerente { get; set; }
        public string supervisor { get; set; }
        public string emailSupervisor { get; set; }
        public string regional { get; set; }
        public string emailRegional { get; set; }
        public decimal latitud { get; set; }
        public decimal longitud { get; set; }
        public System.DateTime fechaActualizacion { get; set; }
    }
}
