//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examenDDLH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class segempleadoscat
    {
        public int codigoEmpleado { get; set; }
        public string nombreUsuario { get; set; }
        public string paterno { get; set; }
        public string materno { get; set; }
        public string nombre { get; set; }
        public string puesto { get; set; }
        public int codigoRol { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string sexo { get; set; }
        public string estatus { get; set; }
        public int codigoTiendaAsignada { get; set; }
        public byte[] password { get; set; }
        public byte vencePassword { get; set; }
        public int diasCambioPassword { get; set; }
        public Nullable<System.DateTime> fechaCambioPassword { get; set; }
        public byte venceUsuario { get; set; }
        public System.DateTime fechaVencimiento { get; set; }
        public int codigoEmpleadoActualizo { get; set; }
        public System.DateTime fechaActualizacion { get; set; }
    }
}
